---

- hosts: deploy_dockerhost
  become: true
  become_method: sudo
  become_user: root
  any_errors_fatal: true
  gather_facts: true
  serial: "{{ serial | default(omit) }}"
  tasks:
    - when: "apply|default(false)"
      block:
        - include_role:
            name: base
        - include_role:
            name: docker
